#!/usr/bin/python3
import pyqrcode
from googlesearch import search
n=input("enter your search:")
url=[]
for i in search(n,stop=1):
	url.append(n)
	qr=pyqrcode.create(i)
	qr.svg("my1qr.svg",scale=10)
	
	
